### ISSUE TITLE
Regarding the bbox branch in UnitBox.py

### ISSUE THREAD

**Issue by yiminglin-ai** [zhimingluo/UnitBox_TF#1]
Hi zhiming, 
I just found your work excellent and offered me a great intuition about the UnitBox network.

I was wondering, in the training stage in UnitBox.py file,  why the bounding box heatmaps inferring the ground truth boxes at all positive pixels are not fed into the network?  

As in the original paper, the network should receive three inputs:
>  the original image, the confidence heatmap inferring a pixel falls in a target object (positive) or not (negative), and the bounding box heatmaps inferring the ground truth boxes at all positive pixels.

Could you tell me how you handle the training and testing with only two inputs, please?

Many thanks,
Yiming

**Comment by zhimingluo** [comment]
Hello,  because I need to work on some other projects, I didn’t have time to finish the code.

Right now, I only test the first part of inferring the score heatmap.
I will finish the bounding box part as soon as possible, or maybe we can work together.

Regards
Zhiming


发件人: Yiming Lin [mailto:notifications@github.com]
发送时间: 2017年5月17日 20:16
收件人: zhimingluo/UnitBox_TF <UnitBox_TF@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [zhimingluo/UnitBox_TF] Regarding the bbox branch in UnitBox.py (#1)


Hi zhiming,
I just found your work excellent and offered me a great intuition about the UnitBox network.

I was wondering, in the training stage in UnitBox.py file, why the bounding box heatmaps inferring the ground truth boxes at all positive pixels are not fed into the network?

As in the original paper, the network should receive three inputs:

the original image, the confidence heatmap inferring a pixel falls in a target object (positive) or not (negative), and the bounding box heatmaps inferring the ground truth boxes at all positive pixels.

Could you tell me how did you handle the training and testing with only two inputs, please?

Many thanks,
Yiming

**Comment by zhimingluo** [comment]
hello, the code for the bounding box part is finished, right now i only test on some images, the code can works but still need a final parameter fine-tuning.

**Comment by yiminglin-ai** [comment]
I have forked the repo and will see if there is anything I could do to make it more complete (at least some readme writings LOL). Good luck with your projects!
